---
# Install Grafana using grafana.grafana collection

- name: 'Create Grafana system user'
  become: true
  ansible.builtin.user:
    name: '{{ grafana_user }}'
    system: true
    shell: /usr/sbin/nologin
    home: '{{ grafana_data_dir }}'
    create_home: false
    groups: []
  register: grafana_user_created

- name: 'Install Grafana using grafana.grafana collection'
  become: true
  ansible.builtin.include_role:
    name: grafana.grafana.grafana
  vars:
    grafana_version: '{{ grafana_version | default(omit) }}'
    grafana_user: '{{ grafana_user }}'
    grafana_group: '{{ grafana_group }}'
    grafana_config_dir: '{{ grafana_config_dir }}'
    grafana_data_dir: '{{ grafana_data_dir }}'
    grafana_logs_dir: '{{ grafana_log_dir }}'
    grafana_plugins_dir: '{{ grafana_plugins_dir }}'
    grafana_provisioning_dir: '{{ grafana_provisioning_dir }}'
