---
# Grafana Service Role - Main Tasks

- name: 'Install Grafana'
  ansible.builtin.import_tasks: install_grafana.yml

- name: 'Configure Grafana'
  ansible.builtin.import_tasks: configure_grafana.yml

- name: 'Create SSL certificate for Grafana'
  ansible.builtin.import_role:
    name: certbot
  vars:
    certbot_name: grafana
    certbot_domains: "{{ grafana_domains }}"
    certbot_email: "{{ user.email }}"

- name: 'Configure nginx for Grafana'
  ansible.builtin.import_role:
    name: nginx_config
  vars:
    nginx_config_template: "nginx.conf.j2"
    nginx_config_service_name: "grafana"
