---
- name: stop kujirad
  become: true
  systemd:
    daemon_reload: no
    name: kujirad
    enabled: false
    state: stopped
  when:
    - cosmovisor_restart and not ansible_check_mode

- name: restart cosmovisor
  become: true
  systemd:
    daemon_reload: true
    name: cosmovisor
    state: restarted
    enabled: true
  when:
    - cosmovisor_restart and not ansible_check_mode
