---
roles:
  - name: geerlingguy.java
  - name: nginxinc.nginx
  - name: nginxinc.nginx_config
  - name: geerlingguy.certbot

collections:
  # Core Ansible collections
  - name: ansible.posix
    version: 2.1.0

  # Community collections
  - name: community.general
    version: 12.5.0
  - name: community.crypto
    version: 3.1.1

  # Monitoring collections
  - name: prometheus.prometheus
  - name: grafana.grafana
    version: ">=3.0.0"

  # Secrets management
  - name: viczem.keepass
