---
- name: Create "{{ user.name }}" With Password
  ansible.builtin.user:
    name: '{{ user.name }}'
    password: "{{ user.password | password_hash('sha512') }}"
    generate_ssh_key: true
    ssh_key_file: '.ssh/{{ user.ssh_key_file }}'
    ssh_key_type: '{{ ssh_key_type }}'
    groups: "sudo"
    append: true
    state: present
    shell: /bin/bash
    update_password: always

- name: Create key folder
  local_action:
    module: file
    path: "{{ user.ssh_key_path }}/"
    state: directory

- name: Copy keys to local machine
  ansible.posix.synchronize:
    mode: pull
    checksum: true
    src: "/home/{{ user.name }}/.ssh/"
    dest: "{{ user.ssh_key_path }}/"

- name: Deploy SSH Public Key
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: present
    key: '/home/{{ user.name }}/.ssh/{{ user.ssh_key_file }}.pub'

- name: Configure passwordless sudo for user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ user.name }}"
    content: "{{ user.name }} ALL=(ALL) NOPASSWD:ALL\n"
    mode: '0440'
    validate: 'visudo -cf %s'

- name: Stop and Start ssh
  service:
    name: ssh
    state: restarted
