---
- name: Create "{{ user_name }}" With Password
  ansible.builtin.user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    generate_ssh_key: yes
    ssh_key_file: "{{ user_ssh_key_file }}"
    groups: "sudo"
    append: yes
    state: present
    shell: /bin/bash
    update_password: always

- name: Copy keys to local machine
  ansible.posix.synchronize:
    mode: pull
    checksum: yes
    src: "/home/{{ user_name }}/.ssh/"
    dest: "{{ user_ssh_key_save_path }}/"

- name: Deploy SSH Public Key
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', '{{ user_ssh_key_save_path }}/{{ user_name }}_id_rsa.pub') }}"

- name: Stop and Start ssh
  service:
    name: ssh
    state: restarted
