---
- name: Update cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: '{{ apt_cache_valid_time | int }}'

- name: Install additional packages
  become: true
  ansible.builtin.package:
    pkg: '{{ item }}'
    state: present
  with_items:
    - "{{ apt_packages }}"
