---
- name: Ensure apt directories exist
  become: true
  ansible.builtin.file:
    path: /var/lib/apt/lists
    state: directory
    mode: '0755'

- name: Initialize apt database
  become: true
  ansible.builtin.command: apt-get update
  args:
    creates: /var/lib/apt/lists/lock
  ignore_errors: true

- name: Update cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: '{{ apt_cache_valid_time | int }}'

- name: Install additional packages
  become: true
  ansible.builtin.package:
    pkg: '{{ item }}'
    state: present
  with_items:
    - "{{ apt_packages }}"
