---
# Sets the amount of time the cache is valid (1h)
cache_valid_time: 3600
apt_packages:
  - sudo
  - wget
  - curl
  - tmux
  - build-essential
  - make
  - git
  - unzip
  - htop
  - mc
  - jq
  - bc
  - unzip
  - tar
  - ca-certificates