---
# Sets the amount of time the cache is valid (1h)
apt_cache_valid_time: 3600
apt_packages:
  - sudo
  - wget
  - unzip
  - htop
  - mc
  - unzip
  - tar
  - ca-certificates
  - logrotate
  - rsync
