---
- name: install package
  become: true
  apt:
    pkg=ufw
    state=present

- name: reset
  become: true
  ufw:
    state=reset

- name: configure rules
  become: true
  ufw:
    name="{{ item.name | default(omit) }}"
    rule="{{ item.rule }}"
    port="{{ item.port | default(omit) }}"
    from="{{ item.from | default(omit) }}"
    to="{{ item.to | default(omit) }}"
    proto="{{ item.proto | default (omit) }}"

  with_flattened:
    - "{{ firewall_ssh_rules }}"
    - "{{ firewall_default_rules }}"
    - "{{ firewall_rules }}"

- name: enable
  become: true
  ufw:
    logging=on
    state=enabled
    policy=deny
