- name: Install self-signed root cert to enable https to self-signed nodes
  become: true
  ansible.builtin.copy:
    src: '{{ tlsgen_ca_root_path }}/{{ tlsgen_ca_root_cert_name }}'
    dest: '/usr/local/share/ca-certificates'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
    force: true

- name: Update ca-certificates
  become: true
  ansible.builtin.command: update-ca-certificates
