---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    cosmosexp_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- block:
    - name: Assert that TLS key and cert path are set
      assert:
        that:
          - "cosmosexp_security_config.cert_file is defined"
          - "cosmosexp_security_config.key_file is defined"

    - name: Check existence of TLS cert file
      stat:
        path: "{{ cosmosexp_security_config.tls_path }}/{{ cosmosexp_security_config.cert_file }}"
      register: __cosmosexp_cert_file

    - name: Check existence of TLS key file
      stat:
        path: "{{ cosmosexp_security_config.tls_path }}/{{ cosmosexp_security_config.key_file }}"
      register: __cosmosexp_key_file

    - name: Assert that TLS key and cert are present
      assert:
        that:
          - "{{ __cosmosexp_cert_file.stat.exists }}"
          - "{{ __cosmosexp_key_file.stat.exists }}"
  when: cosmosexp_security_config is defined

- block:
    - name: Get checksum list from github
      set_fact:
        _checksums: "{{ lookup('url', 'https://github.com/kostage/cosmos-exporter/releases/download/v{{ cosmosexp_version }}/cosmos-exporter_{{ cosmosexp_version }}_checksums.txt', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum for {{ cosmosexp_go_arch }} architecture"
      set_fact:
        cosmosexp_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _checksums }}"
      when:
        - cosmosexp_go_arch in item and cosmosexp_version in item
