---
- name: Copy the cosmovisor systemd service file
  become: true
  template:
    src: cosmovisor.service.j2
    dest: /etc/systemd/system/cosmovisor.service
    owner: root
    group: root
    mode: 0644
  notify: restart cosmovisor
