---
- name: Assert usage of systemd as an init system
  become: true
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Check existence of '{{ cosmovisor_daemon_name }}'
  stat:
    path: '{{ cosmovisor_gobin }}/{{ cosmovisor_daemon_name }}'
  register: __cosmovisor_daemon_file

- name: Assert that '{{ cosmovisor_daemon_name }}' is present
  assert:
    that:
      - "{{ __cosmovisor_daemon_file.stat.exists }}"
