- import_role:
    name: cloudalchemy.prometheus
  vars:
    prometheus_scrape_configs: "{{ lookup('ansible.builtin.template', 'scrape_configs.j2') | from_yaml }}"
    prometheus_alertmanager_config:
      - scheme: http
        static_configs:
          - targets:
            - "127.0.0.1:9093"
