- name: 'Generate scrape configs from template'
  ansible.builtin.set_fact:
    prometheus_scrape_configs: "{{ lookup('template', 'scrape_configs.j2') | from_yaml }}"

- name: 'Import prometheus.prometheus'
  ansible.builtin.import_role:
    name: prometheus.prometheus.prometheus
