- name: Install unzip
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - unzip

- include_role:
    name: cloudalchemy.node_exporter
  vars:
    node_exporter_tls_server_config:
      cert_file: "{{ nodexp_security_config.tls_path }}/{{ nodexp_security_config.cert_file }}"
      key_file: "{{ nodexp_security_config.tls_path }}/{{ nodexp_security_config.key_file }}"
    node_exporter_basic_auth_users:
      prometheus: "{{ nodexp_security_config.password }}"
  when: nodexp_tls

- include_role:
    name: cloudalchemy.node_exporter
  when: not nodexp_tls
