---
ssh_port: 22

ansible_become_password: "{{ lookup('keepass', 'grafana/node', 'password') }}"

user:
  name: "{{ lookup('keepass', 'grafana/node', 'username') }}"
  password: "{{ lookup('keepass', 'grafana/node', 'password') }}"
  sshkey_save_path: '/Users/kostage/Doroshenko/crypto/METRICS/ssh'
  email: "{{ lookup('keepass', 'grafana/email', 'password') }}"

letsencrypt:
  domain_name: "{{ lookup('keepass', 'grafana/domain_name', 'username') }}"
  cert_dir: '/etc/letsencrypt'
  email: "{{ lookup('keepass', 'grafana/email', 'password') }}"

prometheus:
  # nodes
  nodes:
    - name: 'homester'
      password: "{{ lookup('keepass', 'homester/node', 'password') }}"
      ip: "{{ lookup('keepass', 'homester/ip', 'password') }}"

alertmanager_version: latest
alertmanager_receivers:
  - name: 'telegram'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: "{{ lookup('keepass', 'telegram_bot/token', 'password') }}"
        chat_id: "{{ telegram_chat_id }}" # take from inventory due to weird integer var behavior
        disable_notifications: false
        http_config:
          follow_redirects: true
        send_resolved: true
        parse_mode: HTML
alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'telegram'

grafana_security:
  admin_user: "{{ lookup('keepass', 'grafana/node', 'username') }}"
  admin_password: "{{ lookup('keepass', 'grafana/node', 'password') }}"
grafana_server:
  protocol: https
  cert_file: "/etc/letsencrypt/{{ lookup('keepass', 'grafana/domain_name', 'username') }}-fullchain.crt"
  cert_key: "/etc/letsencrypt/{{ lookup('keepass', 'grafana/domain_name', 'username') }}.key"
grafana_alerting: {}

firewall_rules:
- rule: allow
  port: 3000
- rule: allow
  port: 8388
