---
ssh_port: 22

ansible_become_password: "{{ lookup('keepass', 'grafana/node', 'password') }}"

user:
  name: "{{ lookup('keepass', 'grafana/node', 'username') }}"
  password: "{{ lookup('keepass', 'grafana/node', 'password') }}"
  sshkey_save_path: '/Users/kostage/Doroshenko/crypto/METRICS/ssh'
  email: "{{ lookup('keepass', 'grafana/email', 'password') }}"

letsencrypt:
  domain_name: "{{ lookup('keepass', 'grafana/domain_name', 'username') }}"
  cert_dir: '/etc/letsencrypt'
  email: "{{ lookup('keepass', 'grafana/email', 'password') }}"

prometheus:
  # nodes
  nodes:
    - name: 'homester'
      password: "{{ lookup('keepass', 'homester/node', 'password') }}"
      ip: "{{ lookup('keepass', 'homester/ip', 'password') }}"

alertmanager_version: latest
alertmanager_receivers:
  - name: 'telegram'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: "{{ lookup('keepass', 'telegram_bot/token', 'password') }}"
        chat_id: "{{ telegram_chat_id }}" # take from inventory due to weird integer var behavior
        disable_notifications: false
        http_config:
          follow_redirects: true
        send_resolved: true
        parse_mode: HTML
alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'telegram'

grafana_security:
  admin_user: "{{ lookup('keepass', 'grafana/node', 'username') }}"
  admin_password: "{{ lookup('keepass', 'grafana/node', 'password') }}"
grafana_alerting: {}

firewall_rules:
  - rule: allow
    port: 443
  - rule: allow
    port: 80
  - rule: allow
    port: 22

nginx_config_main_template_enable: true

# certbot_admin_email: "{{ lookup('keepass', 'grafana/email', 'password') }}"
# certbot_create_method: webroot
# certbot_create_if_missing: true
# certbot_webroot: /var/www/html
# certbot_certs:
#   - email: "{{ lookup('keepass', 'grafana/email', 'password') }}"
#     domains:
#       - "{{ lookup('keepass', 'grafana/domain_name', 'username') }}"

# certbot_nginx_domains:
#   - "{{ lookup('keepass', 'grafana/domain_name', 'username') }}"
