---
ssh_port: 22

ansible_become_password: "{{ lookup('keepass', 'homester/root', 'password') }}"

# SSH key paths for different connection stages
ssh_root_key_path: '/Users/kostage/Doroshenko/nodes/hetzner'

user:
  name: "{{ lookup('keepass', 'homester/user', 'username') }}"
  password: "{{ lookup('keepass', 'homester/user', 'password') }}"
  email: "{{ lookup('keepass', 'homester/email', 'password') }}"
  ssh_key_path: "/Users/kostage/Doroshenko/nodes/homester/ssh"
  ssh_key_file: "{{ lookup('keepass', 'homester/user', 'username') }}_id_rsa" # & .pub 

tlsgen_common_name: "{{ lookup('keepass', 'homester/ip', 'password') }}"
tlsgen_sans:
  - "IP:{{ lookup('keepass', 'homester/ip', 'password') }}"

node_exporter_tls_server_config:
  cert_file: '{{ tlsgen_remote_path }}/{{ tlsgen_cert_name }}'
  key_file: '{{ tlsgen_remote_path }}/{{ tlsgen_key_name }}'
node_exporter_basic_auth_users:
  prometheus: "{{ lookup('keepass', 'homester/user', 'password') }}"

# Internal service ports
http_port: 80

# Firewall configuration
firewall_rules:
  - rule: allow
    port: 22
  - rule: allow
    port: 443
  - rule: allow
    port: 80
  - rule: allow
    port: 3000

# Package configuration
apt_packages:
  - curl
  - wget
  - git
  - unzip
  - python3
  - python3-pip
  - python3-debian
  - software-properties-common
  - build-essential

grafana_service_admin_user: "{{ lookup('keepass', 'homester/user', 'username') }}"
grafana_service_admin_password: "{{ lookup('keepass', 'homester/user', 'password') }}"
grafana_service_domains:
  - "dashboard.{{ lookup('keepass', 'homester/domain_name', 'username') }}"
  - "www.dashboard.{{ lookup('keepass', 'homester/domain_name', 'username') }}"
grafana_service_primary_domain: "dashboard.{{ lookup('keepass', 'homester/domain_name', 'username') }}"

# Prometheus configuration
prometheus_username: 'prometheus'
prometheus:
  nodes:
    - name: 'headplane'
      ip: "{{ lookup('keepass', 'headplane/ip', 'password') }}"
      password: "{{ lookup('keepass', 'headplane/user', 'password') }}"

# Alertmanager configuration
alertmanager_version: latest
alertmanager_system_user: alertmanager
alertmanager_receivers:
  - name: 'telegram'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: "{{ lookup('keepass', 'telegram_bot/token', 'password') }}"
        chat_id: "{{ telegram_chat_id }}"
        disable_notifications: false
        http_config:
          follow_redirects: true
        send_resolved: true
        parse_mode: HTML

alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'telegram'
