---
ssh_port: 22

ansible_become_password: "{{ lookup('keepass', 'homester/node', 'password') }}"

user:
  name: "{{ lookup('keepass', 'homester/node', 'username') }}"
  password: "{{ lookup('keepass', 'homester/node', 'password') }}"
  sshkey_save_path: '/Users/kostage/Doroshenko/crypto/homester/ssh'
  ssh_key_type: ed25519

tlsgen_common_name: "{{ lookup('keepass', 'homester/ip', 'password') }}"
tlsgen_sans:
  - "IP:{{ lookup('keepass', 'homester/ip', 'password') }}"

node_exporter_tls_server_config:
  cert_file: '{{ tlsgen_remote_path }}/{{ tlsgen_cert_name }}'
  key_file: '{{ tlsgen_remote_path }}/{{ tlsgen_key_name }}'
node_exporter_basic_auth_users:
  prometheus: "{{ lookup('keepass', 'homester/node', 'password') }}"

firewall_rules:
  - rule: allow
    port: 9100 # nodexp
  - rule: allow
    port: 22
