---
ssh_port: 32666
nodexp_tls: yes

remote_user: "{{ lookup('keepass', 'kuji_mainnet_2/node', 'username') }}"
ansible_become_password: "{{ lookup('keepass', 'kuji_mainnet_2/node', 'password') }}"

user:
  name: "{{ lookup('keepass', 'kuji_mainnet_2/node', 'username') }}"
  password: "{{ lookup('keepass', 'kuji_mainnet_2/node', 'password') }}"
  sshkey_save_path: '/Users/kostage/Doroshenko/crypto/KUJIRA2/ssh'

ip: "{{ lookup('keepass', 'kuji_mainnet_2/ip', 'password') }}"

firewall_rules:
  - rule: allow
    port: 26650:26670
    proto: tcp
  - rule: allow
    port: 32666
    proto: tcp
  - rule: allow
    port: 9300
  - rule: allow
    port: 9100
  - rule: allow
    port: 7171

tlsgen_common_name: "{{ lookup('keepass', 'kuji_mainnet_2/ip', 'password') }}"
tlsgen_sans:
  - "IP:{{ lookup('keepass', 'kuji_mainnet_2/ip', 'password') }}"

node_exporter_tls_server_config:
  cert_file: '{{ tlsgen_remote_path }}/{{ tlsgen_cert_name }}'
  key_file: '{{ tlsgen_remote_path }}/{{ tlsgen_key_name }}'
node_exporter_basic_auth_users:
  prometheus: "{{ lookup('keepass', 'kuji_mainnet_2/node', 'password') }}"

cosmosexp_version: '0.3.7'
cosmosexp_args:
  bech-prefix: 'kujira'
  denom: 'kuji'
  denom-coefficient: '1000000'
cosmosexp_security_config:
  tls_path: '{{ tlsgen_remote_path }}'
  cert_file: '{{ tlsgen_cert_name }}'
  key_file: '{{ tlsgen_key_name }}'
  password: "{{ lookup('keepass', 'kuji_mainnet_2/node', 'password') }}"

cosmovisor_version: '0.7.0'
cosmovisor_daemon_home: "/home/{{ lookup('keepass', 'kuji_mainnet_2/node', 'username') }}/.kujira"
cosmovisor_daemon_name: 'kujirad'
