- name: Create user with password and ssh key
  hosts: extra_vpn
  remote_user: root
  tasks:
    - import_role:
        name: user
  ignore_errors: yes
  ignore_unreachable: yes

- name: 'Tune SSH'
  hosts: extra_vpn
  tasks:
    - import_role:
        name: ssh

- name: 'Install packages'
  hosts: extra_vpn
  tasks:
    - import_role:
        name: apt

- name: 'Install docker'
  hosts: extra_vpn
  tasks:
    - import_role:
        name: docker

- name: 'Configure firewall'
  hosts: extra_vpn
  tasks:
    - import_role:
        name: firewall

# !!! tlsgen_common_name is defined for 'extra_vpn' and is not defined for localhost!
- name: Generate TLS cert
  hosts: localhost
  connection: local
  tasks:
    - import_role:
        name: tlsgen
      vars:
        tlsgen_common_name: '0.0.0.0' # fixit
        tlsgen_sans: 'IP:0.0.0.0' # fixit

- name: Create node TLS dir
  hosts: extra_vpn
  become: yes
  tasks:
    - file:
        path: '{{ tlsgen_remote_path }}'
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,g=rwx,o=rx'

- name: Transfer TLS files to remote
  hosts: extra_vpn
  become: yes
  tasks:
    - copy:
        src: '{{ item }}'
        dest: '{{ tlsgen_remote_path }}'
        owner: root
        group: root
        mode: 'u=rw,g=rw,o=r'
        force: yes
      with_items:
        - '{{ tlsgen_path }}/{{ tlsgen_cert_name }}'
        - '{{ tlsgen_path }}/{{ tlsgen_key_name }}'

- name: 'Install Node Exporter'
  hosts: extra_vpn
  tasks:
    - import_role:
        name: cloudalchemy.node_exporter
