---
- name: Create user with password and ssh key
  hosts: headplane_servers
  remote_user: root
  become: false
  tasks:
    - name: 'Install rsync on remote'
      ansible.builtin.import_role:
        name: apt
      vars:
        apt_packages:
          - rsync
      become: false
    - name: 'Create user'
      ansible.builtin.import_role:
        name: user
  ignore_errors: true
  ignore_unreachable: true

- name: 'Install packages'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: apt

- name: 'Allow HTTP for letsencrypt challenge'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import firewall role'
      ansible.builtin.import_role:
        name: firewall
  vars:
    firewall_rules:
      - rule: allow
        port: "{{ http_port }}"

- name: 'Install NGINX'
  hosts: headplane_servers
  become: true
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Install gnupg for apt-key support'
      ansible.builtin.apt:
        name:
          - gnupg
          - curl
        state: present

    - name: 'Import role'
      ansible.builtin.import_role:
        name: nginxinc.nginx

- name: 'Create dedicated service users'
  hosts: headplane_servers
  become: true
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Create headscale system user'
      ansible.builtin.user:
        name: "{{ alertmanager_system_user }}"
        system: true
        shell: /usr/sbin/nologin
        home: /var/lib/headscale
        create_home: false
        groups: []

    - name: 'Create headscale system user'
      ansible.builtin.user:
        name: headscale
        system: true
        shell: /usr/sbin/nologin
        home: /var/lib/headscale
        create_home: false
        groups: []

    - name: 'Create headplane system user'
      ansible.builtin.user:
        name: headplane
        system: true
        shell: /usr/sbin/nologin
        home: /opt/headplane
        create_home: false
        groups: ["headscale"]

- name: 'Install Node Exporter'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import node_exporter role'
      ansible.builtin.import_role:
        name: prometheus.prometheus.node_exporter

- name: 'Install root cert to allow prometheus scrape nodes'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: selfcert

- name: 'Install prometheus'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: prometheus

- name: 'Install alertmanager'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: prometheus.prometheus.alertmanager
#       no_log: false

- name: 'Install Grafana'
  hosts: headplane_servers
  become: true
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import grafana service role'
      ansible.builtin.import_role:
        name: grafana

- name: 'Install Headscale'
  hosts: headplane_servers
  become: true
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import headscale service role'
      ansible.builtin.import_role:
        name: headscale_service

- name: 'Install Headplane'
  hosts: headplane_servers
  become: true
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import headplane service role'
      ansible.builtin.import_role:
        name: headplane_service

- name: 'Setup Grafana OAuth2 Proxy'
  hosts: headplane_servers
  become: true
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import oauth2 proxy role for grafana'
      ansible.builtin.import_role:
        name: oauth2_proxy
      vars:
        oauth2_proxy_name: grafana
        oauth2_proxy_port: "{{ grafana_oauth2_port }}"
        oauth2_proxy_client_id: "{{ grafana_oauth2_client_id }}"
        oauth2_proxy_client_secret: "{{ grafana_oauth2_client_secret }}"
        oauth2_proxy_domains: "{{ grafana_domains }}"
        oauth2_proxy_upstreams: ["http://127.0.0.1:{{ grafana_service_port }}/"]
        oauth2_proxy_authenticated_emails: ["{{ user.email }}"]
        oauth2_proxy_redirect_url: "https://{{ grafana_domains[0] }}/oauth2/callback"
        oauth2_proxy_http_address: "127.0.0.1:{{ grafana_oauth2_port }}"

- name: 'Setup Headplane OAuth2 Proxy'
  hosts: headplane_servers
  become: true
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import oauth2 proxy role for headplane'
      ansible.builtin.import_role:
        name: oauth2_proxy
      vars:
        oauth2_proxy_name: headplane
        oauth2_proxy_port: "{{ headplane_oauth2_port }}"
        oauth2_proxy_client_id: "{{ headplane_oauth2_client_id }}"
        oauth2_proxy_client_secret: "{{ headplane_oauth2_client_secret }}"
        oauth2_proxy_domains: "{{ headplane_domains }}"
        oauth2_proxy_upstreams: ["http://127.0.0.1:{{ headplane_service_port }}/"]
        oauth2_proxy_authenticated_emails: ["{{ user.email }}"]
        oauth2_proxy_redirect_url: "https://{{ headplane_domains[0] }}/oauth2/callback"
        oauth2_proxy_http_address: "127.0.0.1:{{ headplane_oauth2_port }}"

- name: 'Tune SSH'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: ssh

- name: 'Configure firewall'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: firewall