---
- name: Create user with password and ssh key
  hosts: headplane_servers
  remote_user: root
  become: false
  vars:
    ansible_ssh_private_key_file: "{{ ssh_root_key_path }}"
  tasks:
    - name: 'Install rsync on remote'
      ansible.builtin.import_role:
        name: apt
      vars:
        apt_packages:
          - rsync
      become: false
    - name: 'Create user'
      ansible.builtin.import_role:
        name: user
  ignore_errors: true
  ignore_unreachable: true

- name: 'Install packages'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: apt

- name: 'Allow HTTP for letsencrypt challenge'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
    firewall_rules:
      - rule: allow
        port: 80
  tasks:
    - name: 'Import firewall role'
      ansible.builtin.import_role:
        name: firewall

- name: 'Install NGINX'
  hosts: headplane_servers
  become: true
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Install gnupg for apt-key support'
      ansible.builtin.apt:
        name:
          - gnupg
          - curl
        state: present

    - name: 'Import role'
      ansible.builtin.import_role:
        name: nginxinc.nginx

- name: 'Install root cert to allow prometheus scrape nodes'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import selfcert role'
      ansible.builtin.import_role:
        name: selfcert

- name: 'Install Node Exporter'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import node_exporter role'
      ansible.builtin.import_role:
        name: prometheus.prometheus.node_exporter

- name: 'Install prometheus'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import prometheus role'
      ansible.builtin.import_role:
        name: prometheus

- name: 'Install alertmanager'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import alertmanager role'
      ansible.builtin.import_role:
        name: alertmanager

- name: 'Install Headscale'
  hosts: headplane_servers
  become: true
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import headscale service role'
      ansible.builtin.import_role:
        name: headscale_service

- name: 'Install Headplane'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import headplane service role'
      ansible.builtin.import_role:
        name: headplane_service

- name: 'Tune SSH'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: ssh

- name: 'Configure firewall'
  hosts: headplane_servers
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: firewall
