---
- name: Create user with password and ssh key
  hosts: vpn
  remote_user: root
  become: false
  vars:
    ansible_ssh_private_key_file: "{{ ssh_root_key_path }}"
  tasks:
    - name: 'Install rsync on remote'
      ansible.builtin.import_role:
        name: apt
      vars:
        apt_packages:
          - rsync
      become: false
    - name: 'Create user'
      ansible.builtin.import_role:
        name: user
  ignore_errors: true
  ignore_unreachable: true

- name: 'Install packages'
  hosts: vpn
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: apt

- name: 'Allow HTTP for letsencrypt challenge'
  hosts: vpn
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import firewall role'
      ansible.builtin.import_role:
        name: firewall
      vars:
        firewall_rules:
          - rule: allow
            port: "{{ http_port }}"

- name: 'Install NGINX'
  hosts: vpn
  become: true
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Install gnupg for apt-key support'
      ansible.builtin.apt:
        name:
          - gnupg
          - curl
        state: present

    - name: 'Import role'
      ansible.builtin.import_role:
        name: nginxinc.nginx

- name: 'Install Grafana (Native Installation)'
  hosts: vpn
  become: true
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import grafana service role'
      ansible.builtin.import_role:
        name: grafana_service

- name: 'Tune SSH'
  hosts: vpn
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: ssh

- name: 'Configure firewall'
  hosts: vpn
  remote_user: "{{ user.name }}"
  vars:
    ansible_ssh_private_key_file: "{{ user.ssh_key_path }}/{{ user.ssh_key_file }}"
  tasks:
    - name: 'Import role'
      ansible.builtin.import_role:
        name: firewall
