- name: Check ssh key file exists
  stat:
    path: "{{ sshkeygen_directory }}/{{ sshkeygen_username }}_validator_id_rsa"
  register: sshgen_key_file_check

- name: Generate SSH key for user {{ sshkeygen_username }} (TAKES SOME TIME TO FINISH)
  user:
    name: "{{ sshkeygen_username }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: "{{ sshkeygen_directory }}/{{ sshkeygen_username }}_validator_id_rsa"
    ssh_key_passphrase: "{{ sshkeygen_keypass | default('', false) }}"
    force: no
  when: not sshgen_key_file_check.stat.exists

- name: Evaluating the authentication agent & adding the key...
  shell: |
    ssh-add "{{ sshkeygen_directory }}/{{ sshkeygen_username }}_validator_id_rsa"
